👌 IMPROVE failure logging  (#63)
Log run information from mock code execution, and print to stdout on test fixture teardown.

For example:

```
        check_diff_output(res)
    
>       raise
E       RuntimeError: No active exception to reraise

tests/mock_code/test_diff.py:98: RuntimeError
------------------------------------------- Captured log setup -------------------------------------------
DEBUG    pgsu:__init__.py:143 Trying to connect via "psycopg2"...
---------------------------------------- Captured stdout teardown ----------------------------------------
AiiDA mock code logging:
2022-11-22 07:23:37.801306:diff: Init mock code
2022-11-22 07:23:37.802971:diff: Hashed paths: ['_aiidasubmit.sh', '_scheduler-stderr.txt', '_scheduler-stdout.txt', 'file1.txt', 'file2.txt', 'patch.diff']
2022-11-22 07:23:37.803233:diff: Cached directory exists: /Users/chrisjsewell/Documents/GitHub/aiida-testing/tests/mock_code/data/mock-diff-4b5ca93b23993979a24f795147487f1c

======================================== short test summary info =========================================
FAILED tests/mock_code/test_diff.py::test_basic - RuntimeError: No active exception to reraise
```

Also adds `--mock-fail-on-missing` CLI option.

This can be used for CI (e.g. GH Action) runs, where you should likely not be wanting to generate new cache data

Co-authored-by: Leopold Talirz <a-ctalirz@microsoft.com>